version: '3'

networks:
  laravel:

volumes:
  mysql:
  avored:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8050:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - avored
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - mysql:/etc/mysql
    ports:
      - "33065:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www
      - avored
    working_dir: /var/www/backend
    depends_on:
      - php
    networks:
      - laravel

  npm:
    build:
      context: .
      dockerfile: NodeDockerFile
    container_name: npm
    volumes:
      - ./src/frontend:/project
      - avored
    working_dir: /project
    networks:
      - laravel
    ports:
      - "8060:8080"
  
  artisan:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: artisan
      volumes:
        - ./src:/var/www
      depends_on:
        - mysql
      working_dir: /var/www
      entrypoint: ['/var/www/backend/artisan']
      networks:
        - laravel
